### ISSUE TITLE
Multi-courses

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-classroom-backup#24]
A course is composed by a group of students and teachers. 

Any teacher should be able to:
* Create a course. 
* Add other teachers to it.
* Manage its students.
* <del>Associate guides to it</del>.

**Comment by faloi** [comment]
How should we deal with automatic user creation? Perhaps we need the platform to provide metadata before this can be addresed, otherwise the teacher should do it manually (not _that_ bad, but...).

**Comment by flbulgarelli** [comment]
The student should provide that metadata. This is addressed here mumuki/mumuki-platform#313

**Comment by faloi** [comment]
Sure, what I'm saying is we need to resolve mumuki/mumuki-platform#313 first.

**Comment by flbulgarelli** [comment]
Adding guides to a course manually is not necessary anymore, since they are added automcatically when submissions arrive from the proper tenant

**Comment by flbulgarelli** [comment]
Done
